"""Añadir relaciones de Usuario y Cuenta

Revision ID: ed98b2b2c33a
Revises: 6bd35b6c0ce8
Create Date: 2024-11-13 18:23:33.398629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed98b2b2c33a'
down_revision: Union[str, None] = '6bd35b6c0ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
